### ISSUE TITLE
Stycken om Internetanvändning

### ISSUE THREAD

**Issue by Glusch** [hmep/respektikvadrat#3]
Jag ser att du från google docs har kopierat över stycken om *I-KBT och Evidens* samt om *Upplevelse av I-KBT* in i vårt Rstudio-dokument men du har avstått att kopiera över de stycken som följer rubriken *Internetanvändning* samt stycket som följer rubriken *Internetbaserad kognitiv beteendeterapi*. Är din plan att exkludera dessa stycken från vårt färdiga arbete?

**Comment by hmep** [comment]
Nej, jag kom bara inte längre. För gärna in de delar som saknas på de platser som du tycker passar!

**Comment by Glusch** [comment]
Jag har flyttat över dem men är tveksam på var jag tycker att de passar bäst. Nu är de åtminstone inlagda i vår R-fil.
