### ISSUE TITLE
Hålla tabeller och figurer på plats

### ISSUE THREAD

**Issue by Glusch** [hmep/respektikvadrat#8]
Jag tror att följande svar skulle kunna gå att använda sig av för att hålla våra tabeller och figurer på den platsen vi vill.

https://stackoverflow.com/a/33801326/13324075

**Comment by Glusch** [comment]
Denna ger lite mer förståelse kring kodningen men hänvisar sedan till ovan länk som "bästa sätt att göra det på"

https://stackoverflow.com/a/32334582/13324075

**Comment by Glusch** [comment]
Jag ser också att den "_lösningen_" jag implementerade har andra följdbesvär. Formateringen av texten före Figur 1 & 2 har för mig blivit ytterst märklig. Min tolkning är att det när jag knittar 

(1) märks av att figuren inte kommer få plats på den sidan den "borde" få plats på 
(2) figuren flyttas till följande sida
(3) de stycken som följer innan figuren sprids ut på sin sida för att det inte ska bli en massa "tomt utrymme/whitespace (dvs typ ett halvt A4 utan någon text)" innan figuren dyker upp.

Jag antar att en ful lösning är att flytta upp stycken i markdown-dokumentet tills det är "tillräckligt" med text innan sidbrytningen, men det kanske finns ett smidigare sätt att göra det på?

_Edit:_ Jag provade min _dirty-fix_ med att flytta upp text så att sidan innan tabellen/figuren är "full" och det fungerar (se bild 1). Det går även att flytta ned text från föregående sida tills tabellen/figuren flyttas upp på den (se bild 2). Båda sätten är egentligen samma lösning och en väldigt klumpig sådan.

**Bild 1**
![Method I](https://user-images.githubusercontent.com/63606773/79560324-b141e180-80a7-11ea-9928-b11ba9a08db1.PNG)

---

 **Bild 2:**
![Method II](https://user-images.githubusercontent.com/63606773/79560336-b99a1c80-80a7-11ea-8ee3-cbeedf0a2f54.PNG)

**Comment by hmep** [comment]
Borde fungera bra med auto-placeringen nu.
